version: 2.0
jobs:
  build:
    docker:
      - image: circleci/python:3.6.9-stretch
    steps:
      - checkout
      - run:
          name: Install packages
          command: 'sudo apt install gcc-arm-none-eabi binutils-arm-none-eabi'
      - run:
          name: Build app
          command: |
              cd build/build
              cmake ../ -DCMAKE_TOOLCHAIN_FILE=cross_compile.cmake
              make
