version: 2.0
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6.9-stretch
    steps:
      - checkout:
          path: ~/repo/test
      - run:
          name: Install packages
          command: 'sudo apt install gcc-arm-none-eabi binutils-arm-none-eabi cmake'
      - run:
          name: Build app
          command: |
              mkdir ~/repo/test/build/build
              cd ~/repo/test/build/build
              cmake ../ -DCMAKE_TOOLCHAIN_FILE=cross_compile.cmake
              make
  unit-test:
    working_directory: ~/gtest
    docker:
      - image: circleci/python:3.6.9-stretch
    steps:
      - checkout:
          path: ~/repo/test
      - run:
          name: Install packages
          command: 'sudo apt install cmake'
      - run:
          name: Setup GoogleTest
          command: |
              git clone --depth 1 -b release-1.10.0 https://github.com/google/googletest
              cd ~/gtest/googletest
              mkdir build && cd build
              cmake ../
              sudo make install
      - run:
          name: Build tests
          command: |
              cd ~/repo/test/test/build/
              mkdir build && cd build
              cmake ../
              make
      - run:
          name: Run tests
          command: |
              cd ~/repo/test/test/build/build
              ./nrf52832_test.out

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - unit-test

