version: 2.0
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6.9-stretch
    steps:
      - checkout:
          path: ~/repo/test
      - run:
          name: Install packages
          command: 'sudo apt install gcc-arm-none-eabi binutils-arm-none-eabi cmake'
      - run:
          name: Build app
          command: |
              cd ~/repo/test/build/build
              cmake ../ -DCMAKE_TOOLCHAIN_FILE=cross_compile.cmake
              make
